name:  CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: npm ci
      - name: run linter
        run: npm run eslint

      # Mongo is needed for running tests
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: test
        run: npm run test

  deploy:
    if: github.ref == 'refs/heads/f_372_replace_circleci_with_github_actions' || github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: develop deploy
        if: github.ref == 'refs/heads/f_372_replace_circleci_with_github_actions'
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: cd feathers-giveth-develop && git checkout develop && git pull origin develop && [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh && nvm use 10  && npm ci &&  NODE_ENV=develop ./node_modules/.bin/migrate-mongo up && npm run serve
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USERNAME }}
#          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.DEVELOP_PRIVATE_KEY}}

      - name: beta deploy
        if: github.ref == 'refs/heads/main'
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          command: echo "It's not implemented"
          host: ${{ secrets.BETA_HOST }}
          username: ${{ secrets.BETA_USERNAME }}
#          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.BETA_PRIVATE_KEY}}
